name: buildx

on:
 push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - name: Get tag
        id: tagName
        uses: olegtarasov/get-tag@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Docker login
        run: docker login --username timoreymann --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Run Buildx arm
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            . \
            -t timoreymann/snmp_exporter:${{ steps.tagName.outputs.tag }}-arm64v8 \
            -t timoreymann/snmp_exporter:latest-arm64v8
      -
        name: Run Buildx amd
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            . \
            -t timoreymann/snmp_exporter:latest-amd64 \
            -t timoreymann/snmp_exporter:${{ steps.tagName.outputs.tag }}-amd64

